---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgB1WLbc5/dZwc0TdhY5esg23eDpTs9O4W8UNFc4S6LPiESn0jLORSEkf/7JH16kidw3dBXuaGrpSJyDMqBk/6UhbCXn2QRPdru14K2irvdk6PtORrzL6bwPtvpQvCHhWdUtd3LrislQZO5PAmPXr1WbHC6n5qbOdhBceGKHw72h5JnQZDdH7WJBD+OJa02MX8BnUVhF+5CckcvI7HdSKFqSwVnOtG9WxYncxnbb33HjuFh3uXEeyCfwjXg6nTn8Xtqp7TSMwUAk/nqfSgwvHuxFlxHks1GQA4FmFLzzhb0TmfjQgF2mIZlhrPghbH3FK/beqeqrLWvhcLlTGEEgQGHH62xDVvRyuA1vo5b8B5xDNnzn9VcN5WhndSRjEOtrp0fOxL4M6Ddn7+mzNciRDSXUHmvhmKmhhWZT6zXenReNRAfFtm6yZGWuNUhz966roOW11aM2zDzKx9hWJivWqb+Ig8D+gzoYMgdgMQ0zXF7vRD7a0NfNDUYWJCUb3bbItxb8iHVCb3VBII2vJZasmQjbpOX6iH5vfK/4Nb6Mfmk7tQCXL7mhDpXVLKRn72HvOeTcWZ8+FFCwljc83tJzPBtFwWI7aV4bKBX64e2psUQqK7V10QY860/gVWSDCJOtz2+wFRr/w0CcF8G+4om4I9iHnpRIE9po35S9JHB0vXn6A0abc+CJAdau0cc3dDlpXRogSIbCEC3AiNYUGWJMxC9IWlAI2Rk0UDmR
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database
